wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.8
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725030672
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.11.7
      5: 0.17.8
      8:
      - 3
      - 5
      13: windows-amd64
